theme: jekyll-theme-hacker
title: Takeshi Yanagiura
description: I am an empirical economist specializing in higher education policy, causal methods, and machine learning. Currently pursuing Ph.D. in Economics and Education at Teachers College, Columbia University. 
